repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: trailing-whitespace

  - repo: git://github.com/igorshubovych/markdownlint-cli
    rev: v0.23.2
    hooks:
      - id: markdownlint

  - repo: git://github.com/Front/pre-commit-hooks
    rev: v1.0.0
    hooks:
      - id: markdown-toc
      - id: circleci-validate
